In [2]:
import pandas as pd
import sqlite3 
  
con = sqlite3.connect('C:\\Users\\thanv\\ipl_cricket_analytics\\data\\raw\\ipl.db') 
  
def q(sql): 
    """Run a SELECT and show the result as a table.""" 
    return pd.read_sql(sql, con)


def run_sql_file(path): 
    """Read a .sql file and execute every statement in it.""" 
    with open(path, 'r') as f: 
        script = f.read() 
    con.executescript(script) 
    con.commit() 
    print('ran', path)

In [3]:
run_sql_file(r"C:\Users\thanv\ipl_cricket_analytics\sql\practice\09_analysis_views.sql")

ran C:\Users\thanv\ipl_cricket_analytics\sql\practice\09_analysis_views.sql

In [4]:
q("SELECT * FROM v_ball LIMIT 10;")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,5,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,6,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,0,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,1,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,2,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0

In [5]:
q("SELECT * FROM v_innings LIMIT 10;")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
5,335984,2,Delhi Capitals,Rajasthan Royals,132,1,91
6,335985,1,Mumbai Indians,Royal Challengers Bangalore,165,7,120
7,335985,2,Royal Challengers Bangalore,Mumbai Indians,166,5,118
8,335986,1,Sunrisers Hyderabad,Kolkata Knight Riders,110,10,112
9,335986,2,Kolkata Knight Riders,Sunrisers Hyderabad,112,5,114

In [6]:
q("SELECT * FROM v_match_totals LIMIT 10;")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id,first_innings_runs,bat_first_team,chase_won
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,win,BB McCullum,1,6,1,6,46.0,222,Kolkata Knight Riders,0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,win,Yuvraj Singh,2,1,1,2,15.0,207,Sunrisers Hyderabad,0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,win,SPD Smith,4,3,4,4,36.0,184,Mumbai Indians,1
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,win,CA Lynn,5,6,6,6,57.0,183,Gujarat Lions,1
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,win,GJ Maxwell,494,4,494,494,71.0,163,Rising Pune Supergiant,1
5,1082595,2017,6,Bengaluru,2017-04-08,Indian Premier League,5.0,male,T20,T20,...,win,KM Jadhav,1,252,1,1,4.0,157,Royal Challengers Bangalore,0
6,1082596,2017,6,Hyderabad,2017-04-09,Indian Premier League,6.0,male,T20,T20,...,win,Rashid Khan,2,5,2,2,22.0,135,Gujarat Lions,1
7,1082597,2017,6,Mumbai,2017-04-09,Indian Premier League,7.0,male,T20,T20,...,win,N Rana,3,6,3,3,26.0,178,Kolkata Knight Riders,1
8,1082598,2017,6,Indore,2017-04-10,Indian Premier League,8.0,male,T20,T20,...,win,AR Patel,494,1,1,494,70.0,148,Royal Challengers Bangalore,1
9,1082599,2017,6,Pune,2017-04-11,Indian Premier League,9.0,male,T20,T20,...,win,SV Samson,4,252,4,252,180.0,205,Delhi Capitals,0

In [ ]:
n